### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by iamh2o** [jfallmann/MONSDA#51]
Hello Joerg-
(apologies, I could not seem to find a way to msg you directly... so I'm commandeering an issue report) 

I have a very deep appreciation for both WGS analysis and WGS data/compute resource navigation (the latter required to make any meaningful headway with the former). I was impressed with your project. It also is increasingly fascinating how the whole ecosystem around massive genomic data analysis is in such chaos.

Again, I really liked what I saw (and what I think I read between the lines).  I see as a gap in most efforts re:WGS+ analysis, is that managing core compute/storage infra for these pipelines is a very large time and resource drain. And, now my unsolicited offer(of sorts)! 
I feel I put together a really solid (and very much operational) contribution intended to make the resource management easier and understanding costs and usage much less opaque.
I called it [daylily](https://github.com/Daylily-Informatics/daylily). 

There is a substantial snakemake pipeline implemented here, but the compute management/cost tracking/budgeting/etc parts of this project are the most interesting bit IMO. I can swap out workflow managers rather easily. Are these areas of your project you'd be interested in focusing some attention?  I'd be thrilled to chat more (and I'd love to hear further about the results you're seeing)

thank you for hearing me out :-)
--John

**Comment by jfallmann** [comment]
Hi John,
Thanks for reaching out and sharing your thoughts

Checking out your project I'm quite impressed, looks really cool. May be interesting to put some thoughts of my own on this in the future, however, currently this whole project is focused on university groups of which most have access to their own clusters, mitigating the need for budgeting, at least here and now.
Will definitely keep your project in mind

Thanks for reaching out again, feel free to drop me a mail anytime

Cheers,
Joerg
